### Lives in Oregon vs Lives outside of Oregon
```{r}
dk_plot_awareness_alum_assn() +
     facet_wrap(~lives_in_oregon,
                scale = "free_x",
                ncol = 1)
```



### Rural vs not rural
```{r}
dk_plot_awareness_alum_assn() +
     facet_wrap(~rural_or_not,
                scale = "free_x",
                ncol = 1)
```



### Years since graduation

```{r}
dk_plot_awareness_alum_assn() +
     facet_wrap(~years_since_grad_grouped,
                scale = "free_x",
                ncol = 1)
```



### Highest level of education

```{r}

dk_plot_awareness_alum_assn() +
     facet_wrap(~highest_level_of_education_completed_or_in_progress,
                scale = "free_x",
                ncol = 1)
```



### Age

```{r}
dk_plot_awareness_alum_assn() +
     facet_wrap(~age_groups,
                scale = "free_x",
                ncol = 1)

```




### Type of scholarship

```{r}
dk_plot_awareness_alum_assn() +
     facet_wrap(~under_which_ford_family_program_did_you_receive_your_scholarship,
                scale = "free_x",
                ncol = 1)

```









